### ISSUE TITLE
Major Category Tabs don't scale on a small screen

### ISSUE THREAD

**Issue by blairlierman** [washingtonstateuniversity/WSUWP-Plugin-iDonate#119]
On a screen with a width less than ~425px (such as the iPhone6), the major categories tabs don't resize or respond with the rest of the controls.

This throws off Add More Funds indicator as well.

We should look into alternative options for this small of a screen width. Could we reduce the font size or should we use a different control/layout entirely, like a drop down?

iPhone 6 device:
![iphone6alignment](https://cloud.githubusercontent.com/assets/11821485/25110076/3ea1a546-2396-11e7-94f4-85809f8024be.jpg)

iPhone 6 simulator:
![simulatoralignment](https://cloud.githubusercontent.com/assets/11821485/25110088/46e1e18a-2396-11e7-9d59-589f0b5af1d6.png)

**Comment by NateOwen** [comment]
So this is part of the problem of why I was arguing against using the word "SEARCH" with the icon.  Users understand the search icon and it unnecessarily clutters the screen.  I guess moving to a drop down is an option.

**Comment by blairlierman** [comment]
@NateOwen Thank you for the feedback. I see what you mean now, but adding the Search next to the icon clarified the functionality for the people we were demonstrating for. However, we could drop the SEARCH on the smaller screens to deal with this option. I will check and see what resolution this seems to appear at.

**Comment by NateOwen** [comment]
Hey Blair -- today's my last day.  Good luck with this project, it's turning out nicely.

-Nate
