### ISSUE TITLE
Clear Cached JavaScript

### ISSUE THREAD

**Issue by funkSoRubber** [washingtonstateuniversity/WSUWP-Plugin-iDonate#184]
We should have a way for the cached JavaScript to expire or force an update on release

**Comment by funkSoRubber** [comment]
http://wpengineer.com/2292/force-reload-of-scripts-and-stylesheets-in-your-plugin-or-theme/
Basically, add a version as a parameter when calling wp_enqueue_script and it will append it to the script file as a query parameter

**Comment by blairlierman** [comment]
This function may allow us to get that version dynamically: https://code.garyjones.co.uk/get-wordpress-plugin-version

**Comment by philcable** [comment]
@blairlierman @funkSoRubber We usually leverage a variable for this - take a look [here](https://github.com/washingtonstateuniversity/WSUWP-Plugin-Alumni-Awards/blob/master/includes/class-wsuwp-alumni-awards.php#L18) and [here](https://github.com/washingtonstateuniversity/WSUWP-Plugin-Alumni-Awards/blob/master/includes/class-wsuwp-alumni-awards.php#L313-L314) if you want a basic/typical implementation to reference.

Hope that helps!

**Comment by funkSoRubber** [comment]
Attempting to pull it from the plugin.php file using a function, that way we don't have to remember to update a version variable. However, the path is a little more hardcoded than I'd like. Looking into how to grab the plugin name more dynamically
