### ISSUE TITLE
Search for "&" and "and"

### ISSUE THREAD

**Issue by jdcrain** [washingtonstateuniversity/WSUWP-Plugin-iDonate#254]
We should look into possibly treating these the same for fund searches. It can make it a little difficult when donors don't know whether to search for "design & construction" vs "design and construction"

**Comment by jdcrain** [comment]
We could do a few things:
- Do two searches and merge the results
- Drop "and" and "&" in searches
- ???

**Comment by blairlierman** [comment]
Closed as part of #268
