### ISSUE TITLE
Add Styles to Total and Credit Card Disclaimer

### ISSUE THREAD

**Issue by blairlierman** [washingtonstateuniversity/WSUWP-Plugin-iDonate#70]
The new Total and Credit Card Disclaimer elements need to be styled to fit with form.

**Comment by blairlierman** [comment]
@NateOwen Could you take a look at this and issue #73 this week? All of the element additions are in the master branch, but they need some styling work.

If it would be easier for you, I have also updated the Style Guide HTML file in the [UpdatedStyleGuide branch](https://github.com/washingtonstateuniversity/WSUWP-Plugin-iDonate/tree/UpdatedStyleGuide) that you can use.

**Comment by NateOwen** [comment]
Check out https://github.com/washingtonstateuniversity/WSUWP-Plugin-iDonate/pull/80
