### ISSUE TITLE
Indent second line for checkbox text

### ISSUE THREAD

**Issue by blairlierman** [washingtonstateuniversity/WSUWP-Plugin-iDonate#99]
![fund018](https://cloud.githubusercontent.com/assets/11821485/23572093/9cbddeee-0021-11e7-9be7-dfbe67ed92e5.png)

**Comment by NateOwen** [comment]
I couldn't get this to work IF we have a colored checkbox.  If we make it a normal checkbox then it's possible.  You may have better luck.

**Comment by blairlierman** [comment]
@NateOwen I was able to get this working, but I would like you to referring to make sure I didn't do something non-standard or that doesn't fit with the flex box architecture. The PR for it can be viewed here: #101.
